"""Initial entities and relationships

Revision ID: e074a1f5a890
Revises: 
Create Date: 2025-12-05 19:04:16.456245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e074a1f5a890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristic_id'), 'characteristic', ['id'], unique=False)
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=False)
    op.create_table('unit_measurement',
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('abbreviation')
    )
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('order',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('ship_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['status'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['supplier'], ['supplier.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_order_code'), 'order', ['code'], unique=False)
    op.create_table('product',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('um', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['um'], ['unit_measurement.abbreviation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('order_detail',
    sa.Column('order_code', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_code'], ['order.code'], ),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], ),
    sa.PrimaryKeyConstraint('order_code', 'product_code')
    )
    op.create_table('product_characteristic',
    sa.Column('product_code', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], ),
    sa.PrimaryKeyConstraint('product_code', 'characteristic_id')
    )
    op.create_table('product_specification',
    sa.Column('product_code', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ),
    sa.PrimaryKeyConstraint('product_code', 'specification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_specification')
    op.drop_table('product_characteristic')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('specification')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_code'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('user_type')
    op.drop_table('unit_measurement')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_table('order_status')
    op.drop_table('movement')
    op.drop_index(op.f('ix_characteristic_id'), table_name='characteristic')
    op.drop_table('characteristic')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
